### ISSUE TITLE
Can't locate Number/Phone/StubCountry/InternationalPremiumRate.pm

### ISSUE THREAD

**Issue by theory** [DrHyde/perl-modules-Number-Phone#44] opened 2015-09-21 16:06 UTC
One of our servers threw this error:

     Can't locate Number/Phone/StubCountry/InternationalPremiumRate.pm in @INC (you may need to install the Number::Phone::StubCountry::InternationalPremiumRate module) (@INC contains: /usr/local/perl520/lib/site_perl/x86_64-linux-thread-multi /usr/local/perl520/lib/site_perl /usr/local/perl520/lib/vendor_perl/x86_64-linux-thread-multi /usr/local/perl520/lib/vendor_perl /usr/local/perl520/lib/x86_64-linux-thread-multi /usr/local/perl520/lib . /usr/local/iovation/soapserver) at (eval 1815) line 2.

I've been trying to figure out a phone number to trigger it, as one was not logged with the error message, but haven't been able to figure one out. It looks like the country code for InternationalPremiumRate is 979, but I can't get it to choke on any number that starts with 979 (it returns a StubCountry object). But maybe you can see a path where this might occur?

**Comment by DrHyde** [comment] 2015-10-29 16:38
The `use` that tries to load that has always been wrapped in an `eval` so I don't see how this could happen, unless perhaps you've got something that interferes with `die`, `use` or `eval`.

**Comment by theory** [comment] 2015-10-29 16:49
Hah! Sure enough, there's this incredible code in one of the project files:

	$SIG{__DIE__} = sub {
	    return if ($^S); # Ignore if in an eval
	    my $message = $_[0];
	    local $SIG{__DIE__} = sub {
	        # Attempt to do something if the logging of the die fails.
	        # We write to STDERR which is logged to the Apache error_log.
	        # Since something has obviously gone badly wrong, we exit.
	        return if ($^S); # Ignore if in an eval
	        print STDERR "PANIC> Could not log message: $message\n";
	        exit -1;
	    };
	    ERROR($message);
	};

I've no bloody idea who thought this was a good idea, it predates the git history of the project.

**Comment by DrHyde** [comment] 2015-10-29 17:51
but it's checking `$^S`, so should be OK

**Comment by theory** [comment] 2015-10-29 18:49
I never ran across `$^S`, so had no idea how it was supposed to work.

Other than that, I'm not sure what the issue might have been. Can you give me an example phone number that would enter the `eval`? I can maybe try to run it through our production system and try to track down where it gets propagated outside of the `eval`.

**Comment by DrHyde** [comment] 2015-10-29 21:39
Try something like +979 1 1234 5678.

**Comment by DrHyde** [comment] 2016-03-04 15:36
I think this is a duplicate of https://github.com/DrHyde/perl-modules-Number-Phone/issues/57

**Closed by DrHyde** 2016-03-04 15:36 UTC
Labels: unconfirmed
